; Tile index $000
.db $10 $FF $FF $00 $00 $F7 $F7 $08 $00 $E3 $E3 $1C $0E $CF $CF $30 $3F $BF $BF $40 $BF $BF $BF $40 $FF $DF $DF $00 $FF $8E $8E $00
; Tile index $001
.db $10 $FF $FF $00 $00 $DF $DF $20 $00 $8F $8F $70 $E0 $E7 $E7 $18 $D8 $DB $DB $24 $BE $BF $BF $40 $FF $7F $7F $00 $FF $3F $3F $00
; Tile index $002
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $003
.db $FF $FF $00 $FF $FF $FF $03 $FC $FF $FF $3B $C4 $FF $FF $3F $C0 $FF $FF $1F $E0 $FF $FF $7F $80 $FF $FF $7F $80 $FF $FF $3F $C0
; Tile index $004
.db $0C $0C $0C $F3 $6E $6E $6E $91 $EE $EE $EE $11 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $005
.db $0C $0C $0C $F3 $6E $6E $6E $91 $EE $EE $EE $11 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $006
.db $0C $0C $0C $F3 $6E $6E $6E $91 $EE $EE $EE $11 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $007
.db $00 $00 $00 $FF $C0 $C0 $C0 $3F $DC $DC $DC $23 $FC $FC $FC $03 $F8 $F8 $F8 $07 $FE $FE $FE $01 $FE $FE $FE $01 $FC $FC $FC $03
; Tile index $008
.db $FF $FF $00 $FF $3F $3F $00 $FF $23 $23 $00 $FF $03 $03 $00 $FF $07 $07 $00 $FF $01 $01 $00 $FF $01 $01 $00 $FF $03 $03 $00 $FF
; Tile index $009
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $00A
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $00B
.db $FF $FF $00 $FF $FF $FF $03 $FC $FF $FF $3B $C4 $FF $FF $3F $C0 $FF $FF $1F $E0 $FF $FF $7F $80 $FF $FF $7F $80 $FF $FF $3F $C0
; Tile index $00C
.db $FF $FF $00 $FF $FF $FF $C0 $3F $FF $FF $DC $23 $FF $FF $FC $03 $FF $FF $F8 $07 $FF $FF $FE $01 $FF $FF $FE $01 $FF $FF $FC $03
; Tile index $00D
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $00E
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $00F
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $010
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $E0 $00 $FF $FF $C0 $1F $E0 $FF $80 $3F $C0 $FF $00 $7F $80 $FF $00 $7F $80 $FF $00 $7F $80
; Tile index $011
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $012
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $013
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $014
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $015
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $016
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $00 $00 $FF $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $017
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $07 $00 $FF $FF $03 $F8 $07 $FF $01 $FC $03 $FF $00 $FE $01 $FF $00 $FE $01 $FF $00 $FE $01
; Tile index $018
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $019
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $01A
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $01B
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $01C
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $01D
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $01E
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $01F
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $020
.db $C4 $04 $04 $3B $20 $00 $00 $DF $10 $00 $00 $EF $08 $00 $00 $F7 $1C $00 $00 $E3 $30 $0E $00 $C1 $40 $3F $00 $80 $00 $FF $00 $00
; Tile index $021
.db $7F $1F $1F $80 $1F $0E $0E $E0 $14 $04 $04 $EB $20 $00 $00 $DF $70 $00 $00 $8F $18 $E0 $00 $07 $04 $F8 $00 $03 $00 $FE $00 $01
; Tile index $022
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $023
.db $FF $FF $7F $80 $FF $FF $7F $80 $9F $9F $1F $E0 $FF $FF $3F $C0 $3F $3F $3F $C0 $37 $37 $37 $C8 $86 $86 $06 $F9 $E0 $E0 $00 $FF
; Tile index $024
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $77 $77 $77 $88 $76 $76 $76 $89 $30 $30 $30 $CF
; Tile index $025
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $77 $77 $77 $88 $76 $76 $76 $89 $30 $30 $30 $CF
; Tile index $026
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $77 $77 $77 $88 $76 $76 $76 $89 $30 $30 $30 $CF
; Tile index $027
.db $FE $FE $FE $01 $FE $FE $FE $01 $F8 $F8 $F8 $07 $FC $FC $FC $03 $FC $FC $FC $03 $EC $EC $EC $13 $60 $60 $60 $9F $00 $00 $00 $FF
; Tile index $028
.db $03 $03 $00 $FF $01 $01 $00 $FF $01 $01 $00 $FF $07 $07 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $01 $01 $00 $FF $07 $07 $00 $FF
; Tile index $029
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $02A
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $02B
.db $FF $FF $7F $80 $FF $FF $7F $80 $9F $9F $1F $E0 $FF $FF $3F $C0 $3F $3F $3F $C0 $37 $37 $37 $C8 $86 $86 $06 $F9 $E0 $E0 $00 $FF
; Tile index $02C
.db $FF $FF $FE $01 $FF $FF $FE $01 $F9 $F9 $F8 $07 $FF $FF $FC $03 $FC $FC $FC $03 $EC $EC $EC $13 $61 $61 $60 $9F $07 $07 $00 $FF
; Tile index $02D
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $02E
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $02F
.db $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00
; Tile index $030
.db $FF $00 $7F $80 $FF $00 $7F $80 $FF $00 $7F $80 $FF $00 $7F $80 $FF $00 $7F $80 $FF $00 $7F $80 $FF $00 $7F $80 $FF $00 $7F $80
; Tile index $031
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $032
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $033
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $034
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $035
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $036
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $037
.db $FF $00 $FE $01 $FF $00 $FE $01 $FF $00 $FE $01 $FF $00 $FE $01 $FF $00 $FE $01 $FF $00 $FE $01 $FF $00 $FE $01 $FF $00 $FE $01
; Tile index $038
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $039
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $03A
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $03B
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $03C
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $03D
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $03E
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $03F
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $040
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $041
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $042
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $043
.db $F8 $80 $00 $87 $F9 $80 $00 $86 $FF $E0 $00 $E0 $FF $C0 $00 $C0 $FF $C0 $00 $C0 $FF $C8 $00 $C8 $FF $F9 $00 $F9 $FF $FF $00 $FF
; Tile index $044
.db $C3 $00 $00 $3C $C7 $00 $00 $38 $FF $00 $00 $00 $F8 $07 $00 $00 $FC $03 $00 $00 $FE $01 $00 $00 $FF $00 $00 $00 $FF $C0 $00 $C0
; Tile index $045
.db $88 $00 $00 $77 $8C $00 $00 $73 $9F $00 $00 $60 $FF $00 $00 $00 $3F $C0 $00 $00 $E7 $F8 $00 $00 $78 $DF $20 $00 $BD $6F $10 $00
; Tile index $046
.db $71 $00 $00 $8E $79 $00 $00 $86 $FF $00 $00 $00 $E3 $1C $00 $00 $97 $78 $00 $00 $7E $F1 $00 $00 $EB $D7 $20 $00 $E6 $BF $40 $00
; Tile index $047
.db $87 $00 $00 $78 $C7 $00 $00 $38 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $1F $E0 $00 $00 $7F $80 $00 $00 $FF $03 $00 $03
; Tile index $048
.db $1F $01 $00 $E1 $9F $01 $00 $61 $FF $07 $00 $07 $FF $03 $00 $03 $FF $03 $00 $03 $FF $13 $00 $13 $FF $9F $00 $9F $FF $FF $00 $FF
; Tile index $049
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $04A
.db $FF $FF $00 $FF $FF $FF $03 $FC $FF $FF $3B $C4 $FF $FF $3F $C0 $FF $FF $1F $E0 $FF $FF $7F $80 $FF $FF $7F $80 $FF $FF $3F $C0
; Tile index $04B
.db $0C $0C $0C $F3 $6E $6E $6E $91 $EE $EE $EE $11 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $04C
.db $0C $0C $0C $F3 $6E $6E $6E $91 $EE $EE $EE $11 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00
; Tile index $04D
.db $FF $FF $00 $FF $3F $3F $00 $FF $23 $23 $00 $FF $03 $03 $00 $FF $07 $07 $00 $FF $01 $01 $00 $FF $01 $01 $00 $FF $03 $03 $00 $FF
; Tile index $04E
.db $FF $F3 $0F $FC $FF $F3 $7F $8C $FF $C0 $3F $F3 $FF $C0 $3F $F3 $EF $E3 $EF $1C $FF $F3 $7F $8C $F7 $FF $3F $C0 $C2 $DF $1F $E0
; Tile index $04F
.db $1F $FF $E0 $1F $9F $DF $DC $23 $BF $BF $B8 $47 $1F $E7 $F8 $1F $BF $E7 $FF $18 $FF $81 $FE $67 $7F $81 $FE $67 $7F $E7 $FC $1B
; Tile index $050
.db $FF $00 $7F $80 $FF $00 $7F $80 $FF $00 $7F $80 $FF $00 $7F $80 $FF $00 $7F $80 $FF $00 $7F $80 $FF $00 $7F $80 $FF $00 $7F $80
; Tile index $051
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $052
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $053
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $054
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $055
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $056
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00
; Tile index $057
.db $FF $00 $FE $01 $FF $00 $FE $01 $FF $00 $FE $01 $FF $00 $FE $01 $FF $00 $FE $01 $FF $00 $FE $01 $FF $00 $FE $01 $FF $00 $FE $01
; Tile index $058
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $059
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $05A
.db $F3 $00 $0C $FF $FF $00 $F3 $0C $0C $F3 $FF $F3 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $05B
.db $80 $00 $7F $FF $C1 $00 $BE $7F $C1 $00 $BE $7F $C1 $00 $BE $7F $C1 $00 $BE $7F $7F $80 $C0 $BF $7F $80 $DE $A1 $7F $80 $DD $A2
; Tile index $05C
.db $F3 $00 $0C $FF $FF $00 $F3 $0C $0C $F3 $FF $F3 $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $05D
.db $F3 $00 $0C $FF $FF $00 $71 $8E $8E $71 $FB $75 $04 $FB $FF $FB $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $05E
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $05F
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $060
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $061
.db $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $00 $00
; Tile index $062
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $063
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $064
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $065
.db $FF $F6 $09 $C0 $FF $F6 $09 $C0 $FF $F4 $0B $C0 $FF $E4 $1B $C0 $FF $E4 $1B $C0 $FF $CC $33 $80 $F7 $D9 $26 $80 $E7 $B9 $46 $00
; Tile index $066
.db $F3 $5F $A0 $03 $F3 $5F $A0 $03 $F3 $5F $A0 $03 $F3 $DF $20 $03 $FB $DF $20 $03 $79 $EF $10 $01 $3D $EF $10 $01 $1E $E7 $18 $00
; Tile index $067
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $068
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $069
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $06A
.db $FF $FF $7F $80 $FF $FF $7F $80 $9F $9F $1F $E0 $FF $FF $3F $C0 $3F $3F $3F $C0 $37 $37 $37 $C8 $86 $86 $06 $F9 $E0 $E0 $00 $FF
; Tile index $06B
.db $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $77 $77 $77 $88 $76 $76 $76 $89 $30 $30 $30 $CF
; Tile index $06C
.db $FE $FE $FE $01 $FE $FE $FE $01 $F8 $F8 $F8 $07 $FC $FC $FC $03 $FC $FC $FC $03 $EC $EC $EC $13 $60 $60 $60 $9F $00 $00 $00 $FF
; Tile index $06D
.db $03 $03 $00 $FF $01 $01 $00 $FF $01 $01 $00 $FF $07 $07 $00 $FF $00 $00 $00 $FF $00 $00 $00 $FF $01 $01 $00 $FF $07 $07 $00 $FF
; Tile index $06E
.db $F7 $F4 $77 $8B $EF $EC $EF $13 $8F $80 $0F $FC $FF $F0 $7F $8C $E7 $E4 $E7 $1B $03 $00 $03 $FF $C0 $C0 $00 $FF $E0 $E0 $00 $FF
; Tile index $06F
.db $5F $C7 $DE $39 $E7 $E7 $E7 $18 $C3 $03 $C0 $FF $CF $0F $CE $F1 $07 $07 $07 $F8 $00 $00 $00 $FF $03 $03 $00 $FF $07 $07 $00 $FF
; Tile index $070
.db $FF $00 $7F $80 $FF $00 $7F $80 $FF $00 $7F $80 $FF $00 $7F $80 $FF $00 $7F $80 $FF $00 $7F $80 $FF $00 $7F $80 $FF $00 $1C $E3
; Tile index $071
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $3C $C3
; Tile index $072
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $3C $C3 $FF $00 $00 $FF $F9 $01 $06 $F8 $C9 $09 $36 $C0 $C9 $49 $36 $80 $C9 $49 $36 $80
; Tile index $073
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $3C $C3 $FF $00 $00 $FF $9F $80 $60 $1F $93 $90 $6C $03 $93 $92 $6C $01 $93 $92 $6C $01
; Tile index $074
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $3C $C3
; Tile index $075
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $3C $C3
; Tile index $076
.db $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $FF $00 $3C $C3
; Tile index $077
.db $FF $00 $FE $01 $FF $00 $FE $01 $FF $00 $FE $01 $FF $00 $FE $01 $FF $00 $FE $01 $FF $00 $FE $01 $FF $00 $FE $01 $FF $00 $38 $C7
; Tile index $078
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $079
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $07A
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $07B
.db $7E $81 $DD $A3 $FE $01 $AD $53 $FE $01 $A1 $5F $7E $8D $ED $9F $3E $CD $ED $DF $1E $E5 $F5 $EF $0E $F1 $FB $F5 $04 $FB $FF $FB
; Tile index $07C
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $07D
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $07E
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $07F
.db $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00 $00
; Tile index $080
.db $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $081
.db $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $082
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $083
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $084
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $085
.db $F8 $F8 $07 $FF $F7 $F0 $0F $FF $F7 $F0 $0F $FF $F7 $F0 $0F $FF $C0 $C0 $3F $FF $07 $07 $F8 $FF $E3 $E3 $1C $FF $F8 $F8 $07 $FF
; Tile index $086
.db $7F $00 $FF $FF $7F $00 $FF $FF $FF $00 $FF $FF $8C $00 $FF $FF $01 $01 $FE $FF $FC $FC $03 $FF $C1 $C1 $3E $FF $07 $07 $F8 $FF
; Tile index $087
.db $FF $00 $FF $FF $BF $00 $FF $FF $3F $00 $FF $FF $1F $00 $FF $FF $C0 $C0 $3F $FF $3F $3F $C0 $FF $C7 $C7 $38 $FF $F0 $F0 $0F $FF
; Tile index $088
.db $EF $00 $FF $FF $E7 $00 $FF $FF $E7 $00 $FF $FF $83 $00 $FF $FF $18 $18 $E7 $FF $F0 $F0 $0F $FF $C3 $C3 $3C $FF $0F $0F $F0 $FF
; Tile index $089
.db $DE $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $E0 $00 $FF $FF $0F $0F $F0 $FF $3E $3E $C1 $FF $C0 $C0 $3F $FF $FF $FF $00 $FF
; Tile index $08A
.db $FF $FF $00 $FF $3F $3F $C0 $FF $DF $1F $E0 $FF $0F $0F $F0 $FF $80 $80 $7F $FF $03 $03 $FC $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $08B
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $08C
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $08D
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $08E
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $08F
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $090
.db $FF $00 $1C $E3 $FF $00 $00 $FF $9C $63 $63 $FF $80 $7F $7F $FF $80 $7F $7F $FF $80 $7F $7F $FF $80 $7F $7F $FF $80 $7F $7F $FF
; Tile index $091
.db $FF $00 $3C $C3 $FF $00 $00 $FF $3C $C3 $C3 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $092
.db $C9 $49 $36 $80 $C9 $49 $36 $80 $C9 $49 $36 $80 $C9 $49 $36 $80 $C9 $49 $36 $80 $C9 $49 $36 $80 $C9 $49 $36 $80 $C9 $49 $36 $80
; Tile index $093
.db $93 $92 $6C $01 $93 $92 $6C $01 $93 $92 $6C $01 $93 $92 $6C $01 $93 $92 $6C $01 $93 $92 $6C $01 $93 $92 $6C $01 $93 $92 $6C $01
; Tile index $094
.db $FF $00 $3C $C3 $FF $00 $00 $FF $3C $C3 $C3 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $095
.db $FF $00 $3C $C3 $FF $00 $00 $FF $3C $C3 $C3 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $096
.db $FF $00 $3C $C3 $FF $00 $00 $FF $3C $C3 $C3 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $097
.db $FF $00 $38 $C7 $FF $00 $00 $FF $39 $C6 $C6 $FF $01 $FE $FE $FF $01 $FE $FE $FF $01 $FE $FE $FF $01 $FE $FE $FF $01 $FE $FE $FF
; Tile index $098
.db $FF $00 $1C $E3 $FF $00 $00 $FF $1C $E3 $E3 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $099
.db $EE $00 $11 $EE $EE $00 $11 $EE $2E $CE $D1 $E0 $20 $C0 $DF $E0 $2E $C0 $D1 $EE $2E $C0 $D1 $EE $2E $C0 $D1 $EE $2E $CE $D1 $E0
; Tile index $09A
.db $77 $00 $88 $77 $77 $00 $88 $77 $74 $73 $8B $07 $04 $03 $FB $07 $74 $03 $8B $77 $74 $03 $8B $77 $74 $03 $8B $77 $74 $73 $8B $07
; Tile index $09B
.db $FF $00 $3C $C3 $FF $00 $00 $FF $3C $C3 $C3 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $09C
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $09D
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF
; Tile index $09E
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $F8 $00 $FF $FF $F0 $08 $FF $FF $F0 $06 $FF $FF $F8 $01 $FF $FF $FE
; Tile index $09F
.db $00 $FF $FF $C9 $20 $FF $FF $C1 $16 $FF $FF $E1 $00 $FF $FF $E7 $08 $FF $FF $47 $10 $FF $FF $0F $00 $FF $FF $1F $A0 $FF $FF $1F
; Tile index $0A0
.db $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0A1
.db $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0A2
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0A3
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0A4
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0A5
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0A6
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0A7
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0A8
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0A9
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0AA
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0AB
.db $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF
; Tile index $0AC
.db $F0 $F0 $0F $FF $EF $E0 $1F $FF $DF $C0 $3F $FF $BF $80 $7F $FF $BF $80 $7F $FF $7F $00 $FF $FF $7F $00 $FF $FF $7F $00 $FF $FF
; Tile index $0AD
.db $FF $FF $00 $FF $3F $3F $C0 $FF $8F $0F $F0 $FF $C7 $07 $F8 $FF $C7 $07 $F8 $FF $E0 $00 $FF $FF $E7 $00 $FF $FF $EF $00 $FF $FF
; Tile index $0AE
.db $FF $FF $00 $FF $F0 $F0 $0F $FF $EF $E0 $1F $FF $DF $C0 $3F $FF $DF $C0 $3F $FF $1F $00 $FF $FF $9F $00 $FF $FF $DF $00 $FF $FF
; Tile index $0AF
.db $FF $FF $00 $FF $7F $7F $80 $FF $3F $3F $C0 $FF $9F $1F $E0 $FF $93 $13 $EC $FF $CD $01 $FE $FF $DC $00 $FF $FF $C8 $00 $FF $FF
; Tile index $0B0
.db $FF $7F $7F $FF $FF $00 $00 $FF $80 $7F $7F $FF $80 $7F $7F $FF $80 $7F $7F $FF $80 $7F $7F $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0B1
.db $FF $FF $FF $FF $FF $00 $00 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0B2
.db $C9 $49 $36 $80 $C9 $49 $36 $80 $C9 $49 $36 $80 $C9 $49 $36 $80 $FF $7F $00 $80 $FF $00 $00 $FF $FF $FF $FF $FF $FF $00 $00 $FF
; Tile index $0B3
.db $93 $92 $6C $01 $93 $92 $6C $01 $93 $92 $6C $01 $93 $92 $6C $01 $FF $FE $00 $01 $FF $00 $00 $FF $FF $FF $FF $FF $FF $00 $00 $FF
; Tile index $0B4
.db $FF $FF $FF $FF $FF $00 $00 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0B5
.db $FF $FF $FF $FF $FF $00 $00 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0B6
.db $FF $FF $FF $FF $FF $00 $00 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0B7
.db $FF $FE $FE $FF $FF $00 $00 $FF $01 $FE $FE $FF $01 $FE $FE $FF $01 $FE $FE $FF $01 $FE $FE $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0B8
.db $FF $FF $FF $FF $FF $00 $00 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0B9
.db $E0 $C0 $DF $E0 $FF $00 $00 $FF $3F $C0 $C0 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0BA
.db $07 $03 $FB $07 $FF $00 $00 $FF $FC $03 $03 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0BB
.db $FF $FF $FF $FF $FF $00 $00 $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0BC
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0BD
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0BE
.db $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $00 $FF $FF $FF $FF $00 $00 $FF $FF $00 $00 $FF
; Tile index $0BF
.db $00 $FF $FF $9F $40 $FF $FF $8E $20 $FF $FF $C4 $10 $FF $FF $E0 $01 $FF $FF $F0 $06 $FF $FF $F1 $EF $10 $10 $EF $9F $60 $60 $9F
